# Project Configurations
# ----------------------

# Information

url: http://localhost:4000

title: Website title
description: The website meta description can be any length, but for search engine optimization purposes, it is best to limit the description to 156 characters or less.

owner:
  name: Owner Name
  email: owner@email.com

banner:
  developer: # Developer
  developer_url: # http://developer-website.com

# Options

analytics: # UA-XXXXXXXX-X
cache_bust: false
wordpress: # example_theme

link:
  canonical: false
  favicons: true
  feed: false
  google_fonts: # Open+Sans:400,700,400italic,700italic
  script: true
  sitemap: false
  style: true

# Bower Components

components: ['foundation-sites motion-ui']

# Jekyll Configurations
# ---------------------

# Directories

collections: null
data_dir: _data
destination: _site
includes_dir: _includes
layouts_dir: _layouts
plugins_dir: _plugins
source: .

# Reading

encoding: 'utf-8'
exclude: ['*htaccess']
include: []
keep_files: ['.git', '.svn', 'assets']
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
safe: false

# Filtering

future: false
limit_posts: 0
show_drafts: null
unpublished: false

# Plugins

gems: ['jekyll-paginate']
whitelist: []

# Conversion

excerpt_separator: '\n\n'
highlighter: rouge
incremental: false
lsi: false
markdown: kramdown

# Serving

baseurl: ''
detach: false
host: 127.0.0.1
port: 4000

# Outputting

paginate: 7
paginate_path: page:num
permalink: /:categories/:title/
timezone: null

defaults: []
quiet: false

# Markdown

kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6