# Project

folder: _example.com

# Website

url: http://localhost:4000
title: Website Title
description: Website Description
owner:
  name: Owner Name
  email: owner@email.com
  twitter: # username
analytics: # UA-xxxxxxxx-x
banner: Created by Developer | http://website.com

# Options

link:
  canonical: true
  feed: true
  sitemap: true
meta:
  IEedge: true
  openGraph: true
  responsive: true
  twitterCard: true
script:
  jquery: true
  modernizr: true
  oldIE: true
  plugins: true

# Jekyll

include: []
exclude: ['.htaccess']
keep_files: ['.git']
show_drafts: false
future: false
lsi: false
paginate: 7
paginate_path: 'page/:num'
permalink: /:categories/:title/
kramdown:
  auto_ids: false