# Project folder
folder: _example.com

# Website info
url: http://localhost:4000
title: Website Title
description: Website description
owner: Owner Name
email: owner@email.com
analytics: # UA-xxxxxxxx-x
banner: Created by Developer in 2014 | http://website.com

# Website settings
canonical: true
feed: true
feed_count: 14
IEedge: false
javascript: true
jquery: true
modernizr: true
oldIE: true
responsive: true

# Jekyll settings
destination: _site
include: ['']
exclude: ['.htaccess']
keep_files: ['.git', 'sftp-config.json']
show_drafts: false
future: false
lsi: false
paginate: 7
permalink: /:categories/:title/
timezone: # nil
markdown: rdiscount