# Project folder
folder: _example.com

# Website info
url: http://localhost:4000
title: Website Title
description: Website description
owner: Owner Name
email: owner@email.com
banner: Created by Developer in 2013 | http://website.com

# Additional website info
google_analytics_id: # UA-xxxxxxxx-x
google_fonts: # Open+Sans:400,400italic,700,800

# Website options
blog_feed: true
canonical_link: true
ie_edge: false
jquery: false
js_plugins: true
oldie: true
responsive_design: true

# Website sections
header: true
aside: true
footer: true

# Jekyll options
destination: _site
include: ['']
exclude: ['.htaccess']
keep_files: ['.git', 'sftp-config.json']
show_drafts: false
future: false
lsi: false
paginate: 7
permalink: /:categories/:title/
timezone: # nil
markdown: rdiscount