# Project folder
folder: _example.com

# Build directory
destination: _BUILD

# Website info
url: http://localhost:4000
title: Website Title
description: Website description
owner: Owner Name
email: owner@email.com

# Options
jquery: true
google_analytics_id:
banner: Created by Developer in 2013 | http://website.com

# Jekyll options
include: ['']
exclude: ['.htaccess']
keep_files: ['.git', 'sftp-config.json']
show_drafts: false
future: false
lsi: false
paginate: 7
permalink: /:categories/:title/
timezone:
markdown: rdiscount